- name: copy_grafana.repo_file
  ansible.builtin.template:
    src: grafana.repo
    dest: /etc/yum.repos.d/grafana.repo

- name: install_grafana
  ansible.builtin.dnf:
    name: grafana
    state: installed

- name: start_grafana_service
  ansible.builtin.systemd_service:
    name: grafana-server
    state: restarted
    enabled: yes