format_version: 10
pipelines:
  grafana-config-ansible:
    group: Tools
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-1ce9e45:
        git: https://github.com/devops-iterration1/tools-automation-code.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - ansible-play:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
          jobs:
            ansible:
              tasks:
              - exec: {command: ansible-playbook, arguments: [ "-i", "grafana-int.izypsy.cloud,", "-e", "ansible_user=ec2-user", "-e", "ansible_password=DevOps321", "tools-ansible.yml", "-e", "tool_name=grafana" ], run_if: passed}
