format_version: 10
pipelines:
  tools-tf-apply:
    group: Tools
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-1ce9e45:
        git: https://github.com/devops-iterration1/tools-automation-code.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - APPLY:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
          jobs:
            terraform-apply:
              tasks:
              - exec: {command: terraform, arguments: [ "init" ], run_if: passed}
              - exec: {command: terraform, arguments: [ "apply", "-auto-approve" ], run_if: passed}
